# dgi_repo sample configuration.
data_directory: /var/lib/dgi_repo
timezone: UTC
default_namespace: islandora

database:
    name:       dgi_repo
    host:       localhost
    username:   not_a_user
    password:   not_a_pass

db_proxy:
    # Should be a user with only SELECT permissions on a limited set of tables.
    username: reduced_permissions_user
    password: that_pass

# Data made by the system will be owned by this user.
self:
    source: dgi_repo
    username: dgi_repo
drupal_sites:
    # Site ID. User-Agent in inbound requests should match 'Tuque/{name}',
    # like 'Tuque/alpha' for this one
    alpha:
        database:
            type:      mysql # or 'postgres', depending on pymyql or psycopg2, respectively.
            connection:
                host:      www.example.org
                port:      3306
                name:      drupal_db
                username:  example_username
                password:  example_password
            # Optionally, specify the query to use (in case something like
            # Drupal's table name prefixing is being used). This query is passed
            # the username and password hash, in that order.
            query: 'SELECT DISTINCT u.uid, r.name
FROM (
  users u
    LEFT JOIN
  users_roles ON u.uid=users_roles.uid
)
    LEFT JOIN role r ON r.rid=users_roles.rid
WHERE u.name=%s AND u.pass=%s'
    bravo:
        database:
            # Example "IoC" configuration (can similarly pass the query,
            # if necessary (due to different replacement tokens being used or
            # whatever reason)).
            type: ioc
            connection:
                # Identifying the callable to use to get a DB-API 2 connection.
                callable :    !!python/name:psycopg2.connect
                # Optional list of positional args to pass to the above
                # callable.
                args:
                    - one
                    - two
                    - three
                # Optional mapping of keyword arguments to pass to the above
                # callable.
                kwargs:
                    z: zulu
                    y: yankee
                    x: xray
logging:
    # Refer to https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig
    version:                    1
    disable_existing_loggers:   False
    formatters:
        dgi_repo:
            format: '%(asctime)s %(process)d %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        dgi_repo:
            formatter:  dgi_repo
            class:  logging.StreamHandler
            stream: ext://sys.stdout
    root:
        level:      INFO
        handlers:   [dgi_repo]

# Can be used to balance between memory usage and disk IO.
spooled_temp_file_size: 4096
# When in control of download buffering the chunk size to request. Has the same
# trade offs as spooled_temp_file_size, but can also effect packet size.
download_chunk_size: 4096

# A dict passed as kwargs to datetime.timedelta(), see:
# https://docs.python.org/3/library/datetime.html#datetime.timedelta
# "resource" entries with a reference count of zero, older than then given age
# will be deleted in the next garbage collection pass.
unreferenced_age:
    # A crontab entry to run dgi_repo_gc daily will likely be desired,
    # which will delete unreferenced resources older than two days specified
    # here (by default). More aggressive (lower) values may be desirable during
    # larger ingests.
    days: 2
