# dgi_repo sample configuration.
logging:
    log_level: DEBUG

data_directory: /var/lib/dgi_repo

default_namespace: islandora

drupal_sites:
    www.example.org:
        database:
            host:      www.example.org
            port:      3306
            name:      drupal_db
            username:  example_username
            password:  example_password
