# dgi_repo sample configuration.
data_directory: /var/lib/dgi_repo

default_namespace: islandora

drupal_sites:
    alpha:
        database:
            connection:
                callable:   !!python/name:pymysql.connect
                kwargs:
                    host:   www.example.org
                    port:   3306
                    db:     drupal_db
                    user:   example_username
                    passwd: example_password
    bravo:
        database:
            connection:
                callable:     !!python/name:psycopg2.connect
                kwargs:
                    host:     www.example.com
                    port:     5432
                    dbname:   drupal_db
                    user:     example_username
                    password: example_password

logging:
    # Refer to https://docs.python.org/2/library/logging.config.html#logging.config.dictConfig
    version:                    1
    disable_existing_loggers:   False
    formatters:
        dgi_repo:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        dgi_repo:
            formatter:  dgi_repo
            class:  logging.StreamHandler
            stream: ext://sys.stdout
    root:
        level:      INFO
        handlers:   [dgi_repo]
