# dgi_repo sample configuration.
data_directory: /var/lib/dgi_repo

default_namespace: islandora

drupal_sites:
    www.example.org:
        database:
            host:      www.example.org
            port:      3306
            name:      drupal_db
            username:  example_username
            password:  example_password

logging:
    # Refer to https://docs.python.org/2/library/logging.config.html#logging.config.dictConfig
    version:                    1
    disable_existing_loggers:   False
    formatters:
        dgi_repo:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        dgi_repo:
            formatter:  dgi_repo
            class:  logging.StreamHandler
            stream: ext://sys.stdout
    root:
        level:      INFO
        handlers:   [dgi_repo]
